<?php
/**
 * Copyright © Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * See COPYING.txt for license details.
 */
?>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Message Information')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tbody>
                        <tr>
                            <th><?= $block->escapeHtml(__('Recipient Email')) ?></th>
                            <td>
                                <a href="mailto:<?= $block->escapeHtml($block->getRecipientEmail()) ?>">
                                    <?= $block->escapeHtml($block->getRecipientEmail()) ?>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('From')) ?></th>
                            <td><?= $block->escapeHtml($block->getFrom()) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Subject')) ?></th>
                            <td><?= $block->escapeHtml($block->getSubject()) ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="admin__page-section-item order-account-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Sending Information')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tbody> 
                        <tr>
                            <th><?= $block->escapeHtml(__('Sending Time')) ?></th>
                            <td><?= $block->escapeHtml($block->getCreatedAt()) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Status')) ?></th>
                            <td><?= $block->escapeHtml($block->getStatus()) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Error Message')) ?></th>
                            <td><?= $block->escapeHtml($block->getError()) ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<section class="admin__page-section order-view-account-information">
    <iframe id="message-boby" 
            src="<?= $block->escapeHtml($block->getMessageBodyUrl()) ?>" 
            width="100%" 
            frameborder="0" 
            scrolling="no"></iframe>
</section>
<script>
require([], function(){
//<![CDATA[
    var iframe = document.getElementById('message-boby');
    iframe.onload = function() {
        iframe.height = iframe.contentWindow.document.body.scrollHeight
    };
//]]>
});
</script>