<?php
/**
 * Copyright © 2011-2017 Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * 
 * See COPYING.txt for license details.
 */
?>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Message Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tbody>
                        <tr>
                            <th><?php echo __('Recipient Email') ?></th>
                            <td><a href="mailto:<?php echo $this->getRecipientEmail() ?>"><?php echo $this->getRecipientEmail() ?></a></td>
                        </tr>
                        <tr>
                            <th><?php echo __('From') ?></th>
                            <td><?php echo $this->getFrom() ?></td>
                        </tr>                        
                        <tr>
                            <th><?php echo __('Subject') ?></th>
                            <td><?php echo $this->getSubject() ?></td>
                        </tr>                         
                    </tbody>
                </table>
            </div>
        </div>
        <div class="admin__page-section-item order-account-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Sending Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tbody> 
                        <tr>
                            <th><?php echo __('Sending Time') ?></th>
                            <td><?php echo $this->getCreatedAt() ?></td>
                        </tr>                     
                        <tr>
                            <th><?php echo __('Status') ?></th>
                            <td><?php echo $this->getStatus() ?></td>
                        </tr>
                        <tr>
                            <th><?php echo __('Error Message') ?></th>
                            <td><?php echo $this->getError() ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<section class="admin__page-section order-view-account-information">
    <iframe id="message-boby" src="<?php echo $this->getMessageBodyUrl() ?>" width="100%" frameborder="0" scrolling="no"></iframe>
</section>
<script>
require([], function(){
//<![CDATA[
    var iframe = document.getElementById('message-boby');
    iframe.onload = function() {
        iframe.height = iframe.contentWindow.document.body.scrollHeight
    };     
//]]>
});
</script>