<?php
/**
 * Copyright © Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * See COPYING.txt for license details.
 */
?>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= __('Message Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tbody>
                        <tr>
                            <th><?= __('Recipient Email') ?></th>
                            <td>
                                <a href="mailto:<?= $this->getRecipientEmail() ?>">
                                    <?= $this->getRecipientEmail() ?>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <th><?= __('From') ?></th>
                            <td><?= $this->getFrom() ?></td>
                        </tr>
                        <tr>
                            <th><?= __('Subject') ?></th>
                            <td><?= $this->getSubject() ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="admin__page-section-item order-account-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= __('Sending Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tbody> 
                        <tr>
                            <th><?= __('Sending Time') ?></th>
                            <td><?= $this->getCreatedAt() ?></td>
                        </tr>
                        <tr>
                            <th><?= __('Status') ?></th>
                            <td><?= $this->getStatus() ?></td>
                        </tr>
                        <tr>
                            <th><?= __('Error Message') ?></th>
                            <td><?= $this->getError() ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<section class="admin__page-section order-view-account-information">
    <iframe id="message-boby" 
            src="<?= $this->getMessageBodyUrl() ?>" 
            width="100%" 
            frameborder="0" 
            scrolling="no"></iframe>
</section>
<script>
require([], function(){
//<![CDATA[
    var iframe = document.getElementById('message-boby');
    iframe.onload = function() {
        iframe.height = iframe.contentWindow.document.body.scrollHeight
    };
//]]>
});
</script>