<?php
/**
 * Copyright © 2011-2017 Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * 
 * See COPYING.txt for license details.
 */
?>
<script>
require(['prototype'], function(){
//<![CDATA[
    function <?php echo $block->getJsFunction() ?>() {
        var validationMessage = $('<?php echo $block->getHtmlResultId() ?>');
        var params = {
			'host': $('system_smtp_host').value,
			'port': $('system_smtp_port').value,
			'auth': $('system_smtp_auth').value,
			'user': $('system_smtp_user').value,
			'pass': $('system_smtp_pass').value,
			'ssl' : $('system_smtp_ssl').value
        };
        new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxUrl() ?>', {
            parameters: params,
            onSuccess: function(response) {
                var result = '<?php /* @escapeNotVerified */ echo __('Error during smtp connection test.') ?>';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message || result;
                    }
                    if (response.valid == 1) {
                        validationMessage
							.removeClassName('error')
							.removeClassName('hidden')
							.addClassName('success');
                    } else {
                        validationMessage
							.removeClassName('success')
							.removeClassName('hidden')
							.addClassName('error');
                    }
                } catch (e) {
                    validationMessage
						.removeClassName('success')
						.removeClassName('hidden')
						.addClassName('error')
                }
                validationMessage.update(result);
            }
        });
    }
    window.<?php echo $block->getJsFunction() ?> = <?php echo $block->getJsFunction() ?>;
//]]>
});
</script>
<div class="actions actions-smtp-test">
    <button onclick="javascript:<?php echo $block->getJsFunction() ?>(); return false;" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <div id="<?php echo $block->getHtmlResultId() ?>" class="message-test hidden"></div>
</div>
