<?php
/**
 * Copyright © Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * See COPYING.txt for license details.
 */
?>
<script>
require(['prototype'], function(){
//<![CDATA[
    function <?= $block->escapeHtml($block->getJsFunction()) ?>() {
        var summaryId = $('<?= $block->getHtmlResultId() ?>');
        var tooltipId = $('<?= $block->getHtmlResultId() ?>-tooltip');
        var messageId = $('<?= $block->getHtmlResultId() ?>-message');
        var params = {
            'host': $('system_smtp_host').value,
            'port': $('system_smtp_port').value,
            'auth': $('system_smtp_auth').value,
            'user': $('system_smtp_user').value,
            'pass': $('system_smtp_pass').value,
            'ssl' : $('system_smtp_ssl').value
        };
        new Ajax.Request('<?= $block->escapeHtml($block->getAjaxUrl()) ?>', {
            parameters: params,
            onSuccess: function(response) {
                var message = null;
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        message = response.message || message;
                    }
                    if (response.valid == 1) {
                        tooltipId.addClassName('hidden');
                        summaryId.removeClassName('error')
                            .removeClassName('hidden')
                            .addClassName('success')
                            .update('<?= $block->escapeHtml(__('Connection Successful')) ?>');
                    } else {
                        tooltipId.removeClassName('hidden');
                        messageId.update(message);
                        summaryId.removeClassName('success')
                            .removeClassName('hidden')
                            .addClassName('error')
                            .update('<?= $block->escapeHtml(__('Connection Failed')) ?>');
                    }
                } catch (e) {
                    tooltipId.addClassName('hidden');
                    summaryId.removeClassName('success')
                        .removeClassName('hidden')
                        .addClassName('error')
                        .update('<?= $block->escapeHtml(__('Error during smtp connection test.')) ?>');
                }
            }
        });
    }
    window.<?= $block->escapeHtml($block->getJsFunction()) ?> = <?= $block->escapeHtml($block->getJsFunction()) ?>;
//]]>
});
</script>
<div class="actions actions-smtp-test">
    <button onclick="javascript:<?= $block->escapeHtml($block->getJsFunction()) ?>(); return false;"
            type="button"
            id="<?= $block->getHtmlId() ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <div id="<?= $block->getHtmlResultId() ?>" class="summary hidden"></div>
    <div id="<?= $block->getHtmlResultId() ?>-tooltip" class="admin__field-tooltip hidden">
        <span class="admin__field-tooltip-action action-help" tabindex="1"></span>
        <div id="<?= $block->getHtmlResultId() ?>-message" class="admin__field-tooltip-content"></div>
    </div>
</div>
